/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "books-staging",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "vmware-staging",
            "region": "ap-northeast-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyREST",
            "endpoint": "https://mjo6pof0la.execute-api.ap-northeast-1.amazonaws.com/staging",
            "region": "ap-northeast-1"
        },
        {
            "name": "vmware",
            "endpoint": "https://0zmqjh56od.execute-api.ap-northeast-1.amazonaws.com/staging",
            "region": "ap-northeast-1"
        }
    ]
};


export default awsmobile;
